### ISSUE TITLE
Hold API failure leads to fatal error

### ISSUE THREAD

**Issue by andersonjohnf** [amazon-connect/amazon-connect-streams#224]
We're getting random errors where the current call fails to get put on hold when the agent is attempting to transfer via a quickconnect.  We get this failure, and the client thinks the caller is not on hold but the problem is they actually are.  So the agent has no way to take them off hold, and they end up having to hang up on the caller and attempt to call them back.  This is a very serious issue that is having a major impact in our production environment.

Please see error log below:

```
{
	"component": "ccp",
	"level": "ERROR",
	"text": "'holdConnection' API request failed: [object Object]",
	"time": "2020-02-18T18:14:01.087Z",
	"exception": null,
	"objects": [{
		"request": {
			"event": "api_request",
			"requestId": "1582049640862-v94v22kzvd",
			"method": "holdConnection",
			"params": {
				"contactId": "aefd7017-721c-4440-88de-41a8272c2529",
				"connectionId": "aefd7017-721c-4440-88de-41a8272c2529"
			}
		},
		"response": {
			"event": "api_response",
			"requestId": "1582049640862-v94v22kzvd",
			"data": null,
			"err": "{\"type\":\"InvalidStateException\",\"message\":\"Cannot put call on hold: Invalid contact state.\",\"stack\":[\"InvalidStateException: Cannot put call on hold: Invalid contact state.\",\" at constructor.extractError (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:98124)\",\" at constructor.callListeners (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:120027)\",\" at constructor.emit (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:119737)\",\" at constructor.emitEvent (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:113446)\",\" at constructor.e (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:109037)\",\" at r.runTo (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:147328)\",\" at https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:147533\",\" at constructor. (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:109306)\",\" at constructor. (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:113501)\",\" at constructor.callListeners (https://companyremoved.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.js:1:120133)\"]}"
		}
	}],
	"line": 19
}
```

**Comment by andersonjohnf** [comment]
This is what the user sees when this happens:

![image](https://user-images.githubusercontent.com/7416419/74772273-aa405380-525d-11ea-8ceb-93e04bd19fdd.png)

**Comment by kvs6rj** [comment]
Hi, we're investigating this issue. Are you still facing this issue?

**Comment by kvs6rj** [comment]
Resolving -- feel free to re-open if you're still facing the issue
