### ISSUE TITLE
UnknownError: The user xx is already associated with the Amazon Connect instance 8266cdd5-a4b9-4be6-9xxxx

### ISSUE THREAD

**Issue by Swethamr402** [amazon-connect/amazon-connect-streams#235]
Hi Team,

Facing issue with CCP page

We added  connectService.getFederationToken() API, Gettting the below response from this API.

Can you please guide me how can i resolve this issue

UnknownError: The user swetha.mr@dxc.com is already associated with the Amazon Connect instance 8266cdd5-a4b9-4be6-900e-3998e1860c05
    at Object.i [as extractError] (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:17068)
    at constructor.s (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:4020)
    at constructor.callListeners (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:1064)
    at constructor.emit (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:775)
    at constructor.emitEvent (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:9334)
    at constructor.e (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:4976)
    at n.runTo (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:11263)
    at https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:11468
    at constructor.<anonymous> (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:5186)
    at constructor.<anonymous> (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:9389) "UnknownError: The user swetha.mr@dxc.com is already associated with the Amazon Connect instance 8266cdd5-a4b9-4be6-900e-3998e1860c05
    at Object.i [as extractError] (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:17068)
    at constructor.s (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:4020)
    at constructor.callListeners (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:1064)
    at constructor.emit (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:3:775)
    at constructor.emitEvent (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:9334)
    at constructor.e (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:4976)
    at n.runTo (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:11263)
    at https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:11468
    at constructor.<anonymous> (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:5186)
    at constructor.<anonymous> (https://devccp.servicedeskofthefuture.com/js/aws-sdk-2.360.0.min.js:2:9389)"

**Comment by seiyako** [comment]
Hi @Swethamr402, we're sorry but we can't handle an issue not related to StreamsJS here.
