### ISSUE TITLE
Failed to handle AWS API request for method putAgentState

### ISSUE THREAD

**Issue by amicming** [amazon-connect/amazon-connect-streams#316]
Hello,

We've custom CCP (Angular app) running with 1.4.8 stream version. We received below error, not frequently but few times in a months. I also visited https://github.com/amazon-connect/amazon-connect-streams/issues/162.

Any idea? Suggestion?

```
{
        "component": "ccp",
        "level": "ERROR",
        "text": "'putAgentState' API request failed",
        "time": "2020-10-07T17:03:07.122Z",
        "exception": null,
        "objects": [
            {
                "request": {
                    "event": "api_request",
                    "requestId": "NUMERIC-NUMBER-vdqyax5q5c",
                    "method": "putAgentState",
                    "params": {
                        "state": {
                            "agentStateARN": "arn:aws:connect:us-west-2:NUMERIC-NUMBER:instance/ALPHA-NUMERIC-NUMBER/agent-state/ALPHA-NUMERIC-NUMBER",
                            "type": "not_routable",
                            "name": "Not Ready - Outbound Call",
                            "startTimestamp": null
                        }
                    }
                },
                "response": {
                    "event": "api_response",
                    "requestId": "NUMERIC-NUMBER-vdqyax5q5c",
                    "data": null,
                    "err": "{\"type\":\"InvalidStateException\",\"message\":\"Cannot change agent state: Invalid agent or contact state.\",\"stack\":[\"InvalidStateException: Cannot change agent state: Invalid agent or contact state.\",\"    at constructor.extractError (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:98513)\",\"    at constructor.callListeners (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120416)\",\"    at constructor.emit (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120126)\",\"    at constructor.emitEvent (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:113835)\",\"    at constructor.e (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:109426)\",\"    at r.runTo (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:147717)\",\"    at https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:147922\",\"    at constructor.<anonymous> (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:109695)\",\"    at constructor.<anonymous> (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:113890)\",\"    at constructor.callListeners (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120522)\"]}"
                }
            }
        ],
        "line": 13
    },
    {
        "component": "ccp",
        "level": "ERROR",
        "text": "Failed to handle AWS API request for method putAgentState",
        "time": "2020-10-07T17:03:07.122Z",
        "exception": {
            "type": "TypeError",
            "message": "e.stack.split is not a function",
            "stack": [
                "TypeError: e.stack.split is not a function",
                "    at new i (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:246730)",
                "    at o.withException (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:247195)",
                "    at Object.failure (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:372125)",
                "    at Object.failure (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:362356)",
                "    at constructor.<anonymous> (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:270144)",
                "    at constructor.<anonymous> (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:111008)",
                "    at constructor.callListeners (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120416)",
                "    at constructor.emit (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:120126)",
                "    at constructor.emitEvent (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:113835)",
                "    at constructor.e (https://CONNECT-INSTANCE.awsapps.com/connect/ccp-naws/static/streams/connect-streams-min.3bcd111b.js:1:109426)"
            ]
        },
        "objects": [],
        "line": 14
    }
```

**Comment by amicming** [comment]
We have same issue with other user on production. Any Idea ?

**Comment by seiyako** [comment]
Hi @amicming, do you know when this issue occurs? One possibility is that you are calling `agent.setState()` API when the agent is on a connected call. It's not allowed to change agent's status when the agent has a connected call.

**Comment by seiyako** [comment]
I believe that the answer I provided above is the most common reason that returns such an error message. I tested locally and got the same result.
Please reopen the ticket when you have more questions regarding this issue.
