### ISSUE TITLE
calling contact.getAgentConnection() causes infinite logging of a DomException

### ISSUE THREAD

**Issue by ColinMorris83** [amazon-connect/amazon-connect-streams#633]
If I have a contact, if I try to call contact.getAgentConnection() it causes the following error in the console which will just keep going infinitely every second or so:

```
DOMException: Failed to execute 'postMessage' on 'Window': function () {
            var closureArgs = Array.prototype.slice.call(arguments);
            return method.ap...<omitted>... } could not be cloned.
    at WindowIOStream.send (http://localhost:3001/static/js/bundle.js:69733:23)
    at Conduit.sendUpstream (http://localhost:3001/static/js/bundle.js:69907:25)
    at Logger.pushOuterContextCCPLogsUpstream (http://localhost:3001/static/js/bundle.js:67505:21)
    at Logger.wrappedfunction [as pushOuterContextCCPLogsUpstream] (http://localhost:3001/static/js/bundle.js:67582:25)
    at http://localhost:3001/static/js/bundle.js:70236:27
```

This is with the latest version of streams: 2.4.4

Looks like this was introduced in release 2.4.1 as going back to release 2.4.0 does not produce the error.

**Comment by hope-ag** [comment]
facing the same issue on 2.4.4, anyone found a solution?

**Comment by solarsiva** [comment]
I am facing the similar issue. connect-streams.js:29847 DOMException: Failed to execute 'postMessage' on 'Window': function () {
            var closureArgs = Array.prototype.slice.call(arguments);
            return method.ap...<omitted>... } could not be cloned.
    at WindowIOStream.send (http://localhost:3000/static/js/bundle.js:44606:23)
    at Conduit.sendUpstream (http://localhost:3000/static/js/bundle.js:44764:25)
    at Logger.pushOuterContextCCPLogsUpstream (http://localhost:3000/static/js/bundle.js:42670:21)
    at Logger.wrappedfunction [as pushOuterContextCCPLogsUpstream] (http://localhost:3000/static/js/bundle.js:42735:25)
    at http://localhost:3000/static/js/bundle.js:45051:27
