### ISSUE TITLE
Hold/Resume API not properly working.

### ISSUE THREAD

**Issue by sudhirpatel74** [amazon-connect/amazon-connect-streams#735]
Hi Team,

I have embedded CCP by following your instruction given in document.

I have disabled CCP interface rendered in div. later i want to drive all CCP functionality from my custom UI.

I have fetched agent-connection instance and tried to called hold and resume API of amazon-connect. 

Hold API successfully called and its success callback method invoked.
later when I invoked resume API, API called success and successfully callback method invoked.

but still call is not getting resumed.

![image](https://github.com/amazon-connect/amazon-connect-streams/assets/4597340/0c3009e1-5905-4692-8ccd-992578293127)

**Comment by vtrofin** [comment]
Hi team, I'm encountering the same issue here with a custom call panel. Calling the `connection.hold` api works properly while calling the  `connection.resume` api returns success but fails to set the new status to the call panel.  Calling the resume api a second time after received the false "success" status results in an error .

```
{"type":"CallAlreadyResumedException","message":"Error received from Voice Service","stack":["CallAlreadyResumedException: Error received from Voice Service","    at constructor.extractError (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:175015)","    at constructor.callListeners (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203331)","    at constructor.emit (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203041)","    at constructor.emitEvent (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:196721)","    at constructor.e (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:192238)","    at r.runTo (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:230207)","    at https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:230413","    at constructor.<anonymous> (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:192508)","    at constructor.<anonymous> (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:196777)","    at constructor.callListeners (https://development-tokyo-call-center-innovation.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203437)"],"retryStatus":"none","statusCode":400}

```

I'm attaching a [screen cast](https://share.vidyard.com/watch/arbQehFmHNUDKMECnmUj9M) for your convenience. 
Worth mentioning that I've updated to package v.2.6.1. and the issue is there as well. Is there anything that can be done as a workaround? 

My React implementation: 

```
 <Button
      name={isCallOnHold ? "resumeCall" : "holdCall"}
      size="md"
      type="button"
      onClick={toggleHoldCall}
 />


const getAgentConnection = (): connect.BaseConnection => {
    // agent is stored in state
    if (!agent) {
      throw new Error("Agent is not defined")
    }

    const contacts = agent.getContacts(connect.ContactType.VOICE)

    if (!contacts || !contacts.length) {
      throw new Error("No contacts found")
    }

    const contact = contacts[0]

    const activeConnection = contact?.getAgentConnection()

    if (!activeConnection) {
      throw new Error("No Active Connections")
    }

    return activeConnection
  }

const toggleHoldCall = async (): Promise<void> => {
    const activeConnection = getAgentConnection()
    const isOnHold = activeConnection.isOnHold()

    if (isOnHold) {
      activeConnection.resume({
        success: () => console.log("Success resume --->"),
        failure: (err) => console.log("Failed to resume --->", err),
      })
    } else {
      activeConnection.hold({
        success: () => console.log("Success hold --->"),
        failure: (err) => console.log("Failed to hold --->", err),
      })
    }
  }

```

**Comment by vpogudina** [comment]
Thanks for bringing that to our attention. I'll be updating the documentation to clarify the proper use of hold and resume APIs. To make it work you are supposed to call hold and resume on customer connection, not the agent connection. Otherwise code snippet looks good, and should work when you will replace the connection. Please feel free to reopen the ticket if issue persists.
