### ISSUE TITLE
Error clearing Active task

### ISSUE THREAD

**Issue by vtrofin** [amazon-connect/amazon-connect-streams#743]
Somewhat similar to #474 

Hi team, I'm implementing a custom Call Panel which has to be able to accept, reject and end tasks. I am able to accept and reject tasks. Also I'm able to end rejected tasks. 

However, I'm unable to end an [active task](https://gyazo.com/558dc594c2e282c47b25988c0b63ecd2). The custom implementation to end the task results in the following error. I would greatly appreciate some help in figuring out this issue. 
Looks like `contact.clear()` works only for closing the contact after the task has ended but i'm not sure what feature can be used to end the task itself. Based on my tests i'm unable to fetch a connection object for a task. 

```
{"type":"InvalidStateException","message":"Cannot clear contact: invalid state TALKING","stack":["InvalidStateException: Cannot clear contact: invalid state TALKING","    at constructor.extractError (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:175015)","    at constructor.callListeners (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203331)","    at constructor.emit (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203041)","    at constructor.emitEvent (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:196721)","    at constructor.e (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:192238)","    at r.runTo (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:230207)","    at https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:230413","    at constructor.<anonymous> (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:192508)","    at constructor.<anonymous> (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:196777)","    at constructor.callListeners (https://<domain>.my.connect.aws/connect/ccp-naws/static/streams/connect-streams-min.95e70f39.js:1:203437)"],"retryStatus":"none","statusCode":400}'
```

Here is my implementation in React 

````
<Button name="endTask" size="md" type="button" onClick={endTask} />

 const [agent, setAgent] = useState(...)

const getCurrentTask = (): connect.Contact => {
    if (!agent) {
      throw new Error("Agent is not found")
    }

    const contacts = agent.getContacts(connect.ContactType.TASK)

    if (!contacts || !contacts.length) {
      throw new Error("No incoming task found")
    }

    const task = contacts[0]

    return task
  }

const endTask = (): Promise<string> => {
    const task = getCurrentTask()

    return new Promise((resolve, reject) => {
      task.clear({
        success: () => {
          resolve("Success")
        },
        failure: (err) => {
          reject(err)
        },
      })
    })
  }

```

**Comment by vtrofin** [comment]
I've also tried calling the [cleanUp method](https://github.com/amazon-connect/amazon-connect-taskjs/blob/14b3e0aef9b6e1ae1a4fbbdcb23438ca91c19556/src/core/taskSession.js#L45-L47) on the task session but this doesn't seem to help

**Comment by vtrofin** [comment]
Looks like the solution isn't complicated at all. If it helps anyone reading this in the future, the trick is to destroy the connection not to clear the contact. This would work :

```
  const endTask = async (): Promise<string> => {
    const task = getCurrentTask()

    const connections = task.getConnections()
    if (!connections || !connections.length) {
      throw new Error("No connections found for the task")
    }

    const taskConnection = connections[0]

    return new Promise((resolve, reject) => {
      taskConnection.destroy({
        success: () => resolve("Success ending task"),
        failure: (err) => reject(err),
      })
    })
  }

```
