### ISSUE TITLE
Cannot get contact.transfer() to transfer to a queue

### ISSUE THREAD

**Issue by nicklicata-rge** [amazon-connect/amazon-connect-streams#955]
Can this be accomplished with connect-streams-api?

Right now I have an outbound dialing campaign and agents in custom UI using streams.

Flow:
1. outbound dial using connect sdk StartOutboundVoiceContact
2. consumer enters queue and gets answered by agent
3. agent performs a warm transfer to an external 3rd party
4. agent introduces consumer to third party and disconnects 

I do this by placing consumer on hold with connection.hold()
Then I add a connection using contact.addConnection() 
Then I conference all 3 using contact.conferenceConnections()

This all works well, very seamless. But, I need the third party to receive the call as the consumer's phone number for look ups that need to occur on their end. Is this at all possible and if so how to accomplish it? I cannot see anything about caller id in the docs.

UPDATE - this was accomplished by making a new transfer to queue flow and setting the caller id to the custom attribute phone number and exit/resume block at end. Then you connect that transfer flow to a quick connect and double click the quick connect in the connect workspace in the UI.

But, we do not want the AWS Connect workspace shown - I am trying 

```
agent?.getEndpoints(agent?.getAllQueueARNs(), {
  success: function (data) {
	  console.log("getEndpoints", data.endpoints[0]);
  
	  const contact = agent?.getContacts()?.[0];
	  contact?.transfer(data.endpoints[0], {
		  // @ts-ignore -- no type for "success" below??
		  success: (e: any) => {
			  console.log('succ', e)
		  },
		  failure: function (e: any) {
			  console.error("Couldn't add connection to contact. " + e);
			  console.log(e)
		  }
	  })
  }
```

But get nothing but this error

// this is the endpoint for my transfer queue that gets logged
getEndpoints Endpoint {endpointARN: 'arn:aws:connect:us-east-1:2xxxx461:instance/4f…-destination/774d45e0-38de-465f-ab7f-92363bcedd09', endpointId: 'arn:aws:connect:us-east-1:27xxxx0461:instance/4f…-destination/774d45e0-38de-465f-ab7f-92363bcedd09', type: 'queue', name: 'transfer-external', phoneNumber: null, …}

This is the error I get:
Couldn't add connection to contact. {"type":"ValidationException","message":"Cannot transfer contact: channel type unsupported for this operation","stack":["ValidationException","    at constructor.extractError (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:796450)","    at constructor.callListeners (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:826968)","    at constructor.emit (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:826678)","    at constructor.emitEvent (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:820358)","    at constructor.e (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:815875)","    at r.runTo (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:853848)","    at https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:854054","    at constructor.<anonymous> (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:816145)","    at constructor.<anonymous> (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:820414)","    at constructor.callListeners (https://meetings-tech-dev.my.connect.aws/shared-worker/connect-engine.js:2:827074)"],"retryStatus":"none","statusCode":400}

**Comment by nicklicata-rge** [comment]
FYI - I went back to using addConnection and everything is fine.

**Comment by andywang219** [comment]
Hello,

Please refer to the documentation here: https://github.com/amazon-connect/amazon-connect-streams/blob/master/Documentation.md#contacttransfer. Voice is not supported for the transfer API

**Comment by nicklicata-rge** [comment]
yes sorry for wasting your time. I went back to addConnection.
